extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: false      # GitHub Actions 模板常省略 "---"
  truthy:
    check-keys: false   # GitHub Actions 中 "on:" 会被误判
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
